version: '3.7'
name: quarkus-kafka-redpanda-mysql
services:
  blog-backend:
    image: ghcr.io/thegreypilgrim42/quarkus-simple-backend:latest
    container_name: blog-backend
    networks:
      - custom-network
    ports:
      - 9090:9090
    depends_on:
      - mysql-blog
      - redpanda

  text-validator:
    image: ghcr.io/thegreypilgrim42/quarkus-text-validator:latest
    container_name: text-validator
    networks:
      - custom-network
    depends_on:
      - blog-backend
      - redpanda

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.3.6
    container_name: redpanda
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
    volumes:
      - redpanda:/var/lib/redpanda/data
    networks:
      - custom-network
    ports:
      - 19092:19092
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health | grep -E 'Healthy:.+true' || exit 1"]
      interval: 15s
      timeout: 3s
      retries: 5
      start_period: 5s

  mysql-blog:
    image: mysql:8.0
    container_name: mysql-blog
    environment:
      - MYSQL_ROOT_PASSWORD=r0ot-pAsS
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbuser
      - MYSQL_DATABASE=blogdb
    volumes:
      - blog-data:/var/lib/mysql
    networks:
      - custom-network
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  redpanda: null
  blog-data: null

networks:
  custom-network:
    driver: bridge